name: Daily Data Sourcing


on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  

jobs:
  source:
    runs-on: ubuntu-latest
    steps:
      - name: Get JWT Expiration
        id: get-exp
        run: echo "::set-output name=exp::$((($(date +%s%N)/1000000) + (1000 * 60 * 60)))"

      - name: Generate JWT
        id: gen-jwt
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        uses: morzzz007/github-actions-jwt-generator@1.0.1
        with:
          secret: ${{ env.JWT_SECRET }}
          payload: '{ "exp": ${{steps.get-exp.outputs.exp}} }'

      - name: Source RSS
        id: source-rss
        uses: Satak/webrequest-action@v1.2.3
        with:
          url: https://confident-shaw-66a094.netlify.app/functions/source-rss
          headers: '{ "Authorization": "Bearer ${{ steps.gen-jwt.outputs.token }}" }'

      - name: Source FB
        id: source-fb
        uses: Satak/webrequest-action@v1.2.3
        with:
          url: https://confident-shaw-66a094.netlify.app/functions/source-fb
          headers: '{ "Authorization": "Bearer ${{ steps.gen-jwt.outputs.token }}" }'
